apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zmdwor6zh-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zmdwor6zh-dotnet-basic-gitops